# Generated by Django 2.2.3 on 2019-07-21 03:16

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('TY', 'Toyota'), ('CH', 'Chevrolet'), ('FD', 'Ford')], max_length=2)),
                ('color', models.CharField(choices=[('RD', 'Red'), ('BL', 'Blue'), ('GR', 'Green'), ('PR', 'Purple'), ('BK', 'Black'), ('YW', 'Yellow'), ('BW', 'Brown'), ('WH', 'White')], max_length=2)),
                ('fuel_capacity', models.IntegerField()),
                ('leather_seats', models.BooleanField(default=False)),
                ('dark_windows', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('birth_date', models.DateTimeField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('about', models.CharField(max_length=250)),
            ],
        ),
    ]
