# Generated by Django 2.2.3 on 2019-08-08 22:35

from django.db import migrations, models
import forms.validators
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, validators=[forms.validators.validate_contains_only_letters, forms.validators.validate_minimum_length])),
                ('last_name', models.CharField(max_length=75, validators=[forms.validators.validate_contains_only_letters, forms.validators.validate_minimum_length])),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
